phpqa:
  analyzedDirs: ./
  buildDir: build/
  ignoredDirs: vendor
  ignoredFiles: ""
  report: true
  execution: parallel
  output: file
  tools: phpstan
  verbose: true
  extensions:
    - php

phpstan:
  level: 0
  # https://github.com/phpstan/phpstan#configuration
  # standard: tests/.travis/phpstan.neon

report:
  phpstan: build/phpstan.xml

tool:
  phpstan: Hrodic\PHPQAPHPStanAnalyzer\PHPStan